# --
# config for biodcase 2026 - tiny ml (task 3)

# version id
version: 0.1

# datamodule
datamodule:

  # data properties
  target_audio_slice_duration_ms: 3000
  target_sample_rate: 24000

  # feature extraction -> stored as cache
  feature_extraction:
    window_len: 4096
    window_stride: 512
    window_scaling_bits: 12
    mel_n_channels: 40
    mel_low_hz: 125
    mel_high_hz: 7500
    mel_post_scaling_bits: 6

  # normalize
  normalize_features: True

  # dataset
  dataset:
    root_path: '/path/to/the/downloaded/dataset'
    file_ext: '.wav'

  # intermediate
  intermediate:
    root_path: './output/01_intermediate'
    intermediate_id: 'intermediate0'
    filter_files: {'is_used': False, 're_contains': '.*'}
    file_naming: {'target_file_ext': '.npz', 'method': 'keeping_parent_folder'}
    compress: True

  # caching
  caching:
    root_path: './output/02_features'
    cache_id: 'cache0'
    filter_files: {'is_used': False, 're_contains': '.*'}
    file_naming: {'target_file_ext': '.npz', 'method': 'parent_folder_to_filename'}
    compress: True

  # load cache
  load_cache:
    load_on_init: False
    filter_files: {'is_used': False, 're_contains': '.*'}

  # folder structure, splits
  train_folder: 'train'
  validation_folder: 'val'
  test_folder: 'test'

  # load set on init, must be either 'train', 'validation', 'test'
  load_set_on_init: Null

  # other flags
  add_channel_dimension: True
  redo_all: False
  redo_intermediate: False
  redo_cache: False
  verbose: False
  to_torch: True


# dataloader kwargs (for pytorch dataloader)
dataloader_train_kwargs:
  batch_size: 64
  shuffle: true

dataloader_validation_and_test_kwargs:
  batch_size: 32
  shuffle: false


# model
model:
  save_path: './output/03_model'
  device:
    use_cpu: False
    device_name: 'cuda:0'
  criterion: {'module': 'torch.nn', 'attr': 'CrossEntropyLoss', 'kwargs': {}}
  optimizer: {'module': 'torch.optim', 'attr': 'Adam', 'kwargs': {'lr': 0.001, 'betas': [0.9, 0.999]}}
  verbose: False

# model training
model_training:
  num_epochs: 20


# reports
reports:

  # report path
  report_path: './output/04_reports'


# generate embedded code
generate_embedded_code:

  # template directory
  template_dir: './biodcase_tiny/embedded/firmware'

  # gen code dir
  gen_code_dir: './output/05_generated_embedded_code'
  gen_code_source_folder_name: 'src'

  # replace with your serial device
  serial_device: '/dev/ttyUSB0'

  # quantize
  quantize: False