# --
# config for biodcase 2026 - tiny ml (task 3)

# version id
version: 0.1

# datamodule
datamodule:

  # data properties
  target_audio_slice_duration_ms: 3000
  target_sample_rate: 24000
  feature_extraction:
    window_len: 4096
    window_stride: 512
    window_scaling_bits: 12
    mel_n_channels: 40
    mel_low_hz: 125
    mel_high_hz: 7500
    mel_post_scaling_bits: 6

  # dataset
  dataset:
    root_path: '/path/to/the/downloaded/dataset'
    file_ext: '.wav'

  # intermediate
  intermediate:
    root_path: './output/01_intermediate'
    intermediate_id: 'intermediate0'
    redo: False
    filter_files: {'is_used': False, 're_contains': '.*'}
    file_naming: {'target_file_ext': '.npz', 'method': 'keeping_parent_folder'}
    compress: True

  # caching
  caching:
    root_path: './output/02_features'
    cache_id: 'cache0'
    redo: False
    filter_files: {'is_used': False, 're_contains': '.*'}
    file_naming: {'target_file_ext': '.npz', 'method': 'parent_folder_to_filename'}
    compress: True

    # todo:
    # add feature extraction module
    # feature_extraction:
    #   module: 'feature_extractions.xxx'
    #   attr: 'SoundFeatures'

  load_cache:
    load_on_init: False
    filter_files: {'is_used': False, 're_contains': '.*'}

  # folder structure, splits
  train_folder: 'train'
  validation_folder: 'val'
  test_folder: 'test'

  redo: False
  verbose: False
  to_torch: True


# dataloader kwargs (for pytorch dataloader)
dataloader_kwargs:
  batch_size: 64
  shuffle: true


# pipeline
pipeline:

  # data preprocessing
  data_preprocessing:
    audio_slice_duration_ms: 3000
    sample_rate: 16000

  # feature extraction
  feature_extraction:
    window_len: 4096
    window_stride: 512
    window_scaling_bits: 12
    mel_n_channels: 40
    mel_low_hz: 125
    mel_high_hz: 7500
    mel_post_scaling_bits: 6

  # model training
  model_training:
    seed: 42
    n_epochs: 20
    shuffle_buff_n: 10000
    batch_size: 128
    early_stopping:
      patience: 5

  # embedded code
  embedded_code_generation:

    # replace with your serial device
    serial_device: "/dev/ttyUSB0"