# --
# config for biodcase 2026 - tiny ml (task 3)

# version id
version: 0.2

# skip deployment - useful for model testing only
skip_deployment_flag: False

# datamodule
datamodule:

  # data properties
  target_audio_slice_duration_ms: 3000
  target_sample_rate: 24000

  # feature extraction -> stored as cache
  feature_extraction:
    window_len: 4096
    window_stride: 512
    window_scaling_bits: 12
    mel_n_channels: 40
    mel_low_hz: 125
    mel_high_hz: 7500
    mel_post_scaling_bits: 6

  # feature handler gets this additionally and feature extraction above
  feature_handler_add_kwargs:
    target_sample_rate: 24000
    transpose_features_extracted: True
    normalize_features: True
    to_float: True
    to_torch: True
    add_channel_dimension: True
    add_batch_dimension: False
    channel_dimension_at_end: False

  # dataset
  dataset:
    root_path: '../2026/Data/BioDCASE_2026_Task_3_TinyML_Dataset_V1'
    file_ext: '.wav'

  # intermediate
  intermediate:
    root_path: './output/01_intermediate'
    intermediate_id: 'intermediate0'
    filter_files: {'is_used': False, 're_contains': '.*'}
    file_naming: {'target_file_ext': '.npz', 'method': 'keeping_parent_folder'}
    compress: True

  # caching
  caching:
    root_path: './output/02_features'
    cache_id: 'cache0'
    filter_files: {'is_used': False, 're_contains': '.*'}
    file_naming: {'target_file_ext': '.npz', 'method': 'keeping_parent_folder'}
    compress: True

  # load cache
  load_cache:
    load_on_init: False
    filter_files: {'is_used': False, 're_contains': '.*'}

  # folder structure, splits
  train_folder: 'Train'
  validation_folder: 'Validation'
  test_folder: 'Validation'

  # load set on init, must be either 'train', 'validation', 'test'
  load_set_on_init: Null

  # other flags
  redo_all: False
  redo_intermediate: False
  redo_cache: False
  verbose: False


# --
# choose either pytorch or tensorflow framework
# for pytorch framework run 'python biodcase2026_tiny_ml_pytorch'

# pytorch framework
pytorch_framework:

  dataloader_train_kwargs:
    batch_size: 32
    shuffle: true

  dataloader_validation_and_test_kwargs:
    batch_size: 32
    shuffle: false

  model:
    module: pipeline_pytorch.model_tiny_ml
    attr: Baseline
    args: []
    kwargs:
      device:
        use_cpu: False
        device_name: 'cuda:0'
      criterion: {'module': 'torch.nn', 'attr': 'CrossEntropyLoss', 'kwargs': {}}
      optimizer: {'module': 'torch.optim', 'attr': 'Adam', 'kwargs': {'lr': 0.001, 'betas': [0.9, 0.999]}}
      verbose: False

  model_training:
    num_epochs: 100

# tensorflow framework
tensorflow_framework:

  # model training - tensorflow
  model_training:
    seed: 42
    n_epochs: 100
    shuffle_buff_n: 10000
    batch_size: 32
    early_stopping:
      patience: 100


# generate embedded code
generate_embedded_code:

  # template directory
  template_dir: './biodcase_tiny/embedded/firmware'

  # gen code dir
  gen_code_dir: './output/05_generated_embedded_code'
  gen_code_source_folder_name: 'src'

  # replace with your serial device
  serial_device: '/dev/ttyUSB0'

  # quantize
  quantize: True