# USAGE:
# 1) Place the zip file(s) of the submission(s) to evaluate in the SUBMISSIONS_DIR folder.
# 2) Adjust the SUBMISSIONS_DIR and RESULT_FILE paths in the CONFIGURATION section below if needed.
# 3) Run this script. It will create a CSV file with the evaluation results for each submission.
# 
# HOW IT WORKS:
# This script is designed to evaluate one or more task3 submissions packaged as zip files. Each
# zip file can contain one or more top-level folders with '_task3' in their name, each representing
# an independent submission to evaluate. For each such submission folder, the script creates a
# temporary copy of the current project template, extracts the submission files on top of it according
# to specific rules, and runs the submission_test.py script in an isolated environment. The results
# are collected from a yaml file generated by submission_test.py and saved into a CSV file for easy comparison.

# INFO: 
# For single submission testing, put only the zip file of that submission in the folder and run this script, then check the csv for the results. 
# Doesnt use generated code from submission, only the model files, config_submission.yaml, feature_handler.py, inference_handler.py and custom code (placed in root) from the zip file.
# Important: script is dependent on the folder structure being correct, or else the evaluation of the submission will fail. The error will be saved in the csv file as well.
# Important: needs keras/pth and tflite model, so no possibility to only submit one of them, otherwise the evaluation will fail and the error will be saved in the csv file as well.

#PROBLEM:
# If contestant submits his own submission_test.py, this will be used instead of the original one, which can be exploited to get unfair advantages... NEEDS TO BE FIXED.
# Is the generated code folder also copied?
# Also the possibility to submit custom code brings the potential to inject malicious code, so this script should only be run in a secure environment and the 
# submissions should be checked manually before running the evaluation.
# This script should not be public and only used by the organizers to evaluate the submissions, so the above points are not a big problem, but should be kept in mind.

import os
import sys
import shutil
import tempfile
import subprocess
import zipfile
import csv
import yaml
from pathlib import Path
from submission.rank_submissions.convert_csv_to_yaml import convert_csv_to_yaml

# CONFIGURATION (adjust these paths as needed)
SUBMISSIONS_DIR = Path("/mnt/c/Users/saphi/Desktop/dummy_submissions")
RESULT_FILE = Path("./submission/rank_submissions/eval_results.csv")
VERBOSE_SUBPROCESS = True  # set to False to suppress live output from submission_test.py

# Folder and files that should NOT be copied to the temp folder to save time.
# The placeholder model files below are excluded so the contestant's model is always used.
# TODO: maybe change to a whitelist approach (only copy what is needed)
IGNORE_PATTERNS = shutil.ignore_patterns(
    "*.zip", 
    "*.git", 
    "__pycache__", 
    ".venv", 
    ".vscode",
    "evaluate_submissions.py", 
    "eval_results.csv",
    "output",
    "docs",
    "test_Baseline.pth",
    "test_Baseline.tflite",
    "test_model.keras",
    "test_model.tflite",
)

# Directories inside the template that must not be searched when looking for files to overwrite.
# Keeps the same spirit as IGNORE_PATTERNS above.
SCAN_IGNORE_DIRS = {".git", "__pycache__", ".venv", ".vscode", "output", "docs"}

# Files and folders from the zip that must never be placed into the temp clone,
# regardless of extraction rule. Prevents contestants from overwriting evaluation
# infrastructure or injecting generated/malicious code.
ZIP_EXTRACTION_BLOCKLIST_FILES   = {"submission_test.py", "evaluate_submissions.py"}
ZIP_EXTRACTION_BLOCKLIST_FOLDERS = {"your_generated_code"}

# Subfolder inside the zip task folder that contains model files.
# These are always placed into submission/your_submission_model/ in the temp clone.
ZIP_MODEL_SUBFOLDER = "your_submission_model"

# Destination for model files inside the temp clone (relative to temp root).
TEMP_MODEL_DIR = Path("submission") / "your_submission_model"

# CSV columns that map 1-to-1 to keys in submission_results.yaml
RESULT_FIELDS = [
    "accuracy_inference",
    "accuracy_tflite",
    "roc_auc_inference",
    "roc_auc_tflite",
    "model_size_inference_bytes",
    "model_size_tflite_bytes",
    "macs_inference",
    "macs_tflite",
    "num_params_inference",
    "num_params_tflite",
    "embedded_time_ms_setup",
    "embedded_time_ms_preprocessing",
    "embedded_time_ms_model",
    "embedded_time_ms_total",
    "embedded_ram_usage_bytes",
]


def _build_template_file_index(template_root):
    """
    Walk the template tree (excluding SCAN_IGNORE_DIRS) and return a dict mapping
    filename -> list of absolute Paths where that filename exists.
    Used to locate files that should be overwritten by submission files.
    """
    index = {}
    for dirpath, dirnames, filenames in os.walk(template_root):
        # prune ignored directories in-place so os.walk does not descend into them
        dirnames[:] = [d for d in dirnames if d not in SCAN_IGNORE_DIRS]
        for filename in filenames:
            index.setdefault(filename, []).append(Path(dirpath) / filename)
    return index


def _get_task3_folders(zip_path):
    """
    Return a sorted list of top-level folder names inside the zip that contain '_task3'.
    Each such folder represents one independent submission to evaluate.
    """
    task3_folders = set()
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        for member in zip_ref.infolist():
            parts = Path(member.filename).parts
            if len(parts) >= 2 and "_task3" in parts[0]:
                task3_folders.add(parts[0])
    return sorted(task3_folders)


def _extract_submission_files(zip_path, temp_path, task3_folder):
    """
    Extract submission files from one task3 subfolder inside the zip into temp_path.

    Zip layout expected:
        biodcase_2026_task3_submission_package.zip/
            <lastname>_task3_<N>/
                config_submission.yaml
                <replacement or additional files>
                your_submission_model/
                    <model_name>.pth / .keras / .tflite
                your_generated_code/
                    src/ (optional)

    Placement rules:
    - Files inside your_submission_model/ -> always go to submission/your_submission_model/
      in the temp clone, regardless of what is already there.
    - All other files -> search the template tree for a file with the same name and
      overwrite it in place (handles config_submission.yaml, feature_handler.py, etc.).
    - If no match is found in the template -> place at temp root so relative imports work
      (handles new custom modules added by the contestant).

    Blocklist (ZIP_EXTRACTION_BLOCKLIST_FILES / ZIP_EXTRACTION_BLOCKLIST_FOLDERS):
    - Any file whose name is in ZIP_EXTRACTION_BLOCKLIST_FILES is silently skipped.
    - Any file whose path passes through a folder in ZIP_EXTRACTION_BLOCKLIST_FOLDERS
      is silently skipped. This prevents contestants from overwriting evaluation
      infrastructure (submission_test.py) or injecting generated/malicious code.
    """

    # build index only once, before writing anything
    template_index = _build_template_file_index(temp_path)

    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        for member in zip_ref.infolist():
            member_path = Path(member.filename)

            # skip directories themselves
            if member.is_dir():
                continue

            parts = member_path.parts

            # only process files from the specific task3 folder being evaluated
            if len(parts) < 2 or parts[0] != task3_folder:
                continue

            # path of this file relative to its task subfolder (e.g. your_submission_model/Mustermann.pth)
            relative_file_path = Path(*parts[1:])
            filename = relative_file_path.name

            # blocklist check: skip protected filenames
            if filename in ZIP_EXTRACTION_BLOCKLIST_FILES:
                print(f"  [BLOCKED] '{filename}' is not allowed from zip submissions, skipping.")
                continue

            # blocklist check: skip anything inside a protected folder
            if any(part in ZIP_EXTRACTION_BLOCKLIST_FOLDERS for part in relative_file_path.parts[:-1]):
                print(f"  [BLOCKED] '{relative_file_path}' is inside a blocked folder, skipping.")
                continue

            file_bytes = zip_ref.read(member.filename)

            # rule 1: model files always land in submission/your_submission_model/
            if relative_file_path.parts[0] == ZIP_MODEL_SUBFOLDER:
                dest = temp_path / TEMP_MODEL_DIR / filename
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_bytes(file_bytes)

            # rule 2: known file -> overwrite every matching location in the template tree
            elif filename in template_index:
                for existing_path in template_index[filename]:
                    existing_path.write_bytes(file_bytes)

            # rule 3: new file not in template -> place at temp root
            else:
                dest = temp_path / filename
                dest.write_bytes(file_bytes)


def _collect_results(temp_path):
    """
    Read submission_results.yaml written by submission_test.py and return a flat dict
    with one entry per RESULT_FIELDS key, or None if the file is missing.
    """
    results_yaml = temp_path / "submission" / "reports" / "submission_results.yaml"

    if not results_yaml.is_file():
        return None

    data = yaml.safe_load(results_yaml.read_text())
    submission_results = data.get("submission_results", {})

    return {field: submission_results.get(field, "N/A") for field in RESULT_FIELDS}


def _run_subprocess(cmd, cwd, timeout):
    """
    Run a subprocess, streaming its output live to the console if VERBOSE_SUBPROCESS is True,
    or capturing it silently otherwise.
    Returns (returncode, output_string, timed_out).
    """
    output_lines = []

    try:
        if VERBOSE_SUBPROCESS:
            process = subprocess.Popen(
                cmd,
                cwd=cwd,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,  # merge stderr into stdout so both print in order
                text=True,
                bufsize=1,  # line-buffered
            )
            # stream output line by line while the process runs
            for line in process.stdout:
                print(line, end="", flush=True)
                output_lines.append(line)
            process.wait(timeout=timeout)
            return process.returncode, "".join(output_lines), False

        else:
            result = subprocess.run(
                cmd,
                cwd=cwd,
                capture_output=True,
                text=True,
                timeout=timeout,
            )
            return result.returncode, result.stdout + result.stderr, False

    except subprocess.TimeoutExpired:
        process.kill()
        process.wait()
        return -1, "".join(output_lines), True


def evaluation_process(zip_path, task3_folder, template_dir, python_executable):
    """
    Copies the current project version to a temp folder, extracts one task3 submission on top
    of it, and runs submission/submission_test.py using the original .venv.
    Returns (output_string, result_fields_dict_or_None).
    """

    #create isolated temp directory
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)

        print(f"\nCreated temporary directory at {temp_path} for evaluating {task3_folder}")
        print(f"Template directory: {template_dir}")
        
        # copy current project version to temp directory (ignoring .venv, zip files etc.)
        # dirs_exist_ok=True allows writing into the freshly created temp directory
        shutil.copytree(template_dir, temp_path, ignore=IGNORE_PATTERNS, dirs_exist_ok=True)
        
        # extract only this task3 folder's files into the temp clone:
        # - model files go to submission/your_submission_model/
        # - known files overwrite their counterpart anywhere in the template tree
        # - new files are placed at temp root
        # - blocklisted files and folders are silently skipped
        try:
            _extract_submission_files(zip_path, temp_path, task3_folder)
        except Exception as e:
            return f"ERROR: Defektes Zip-Archiv ({str(e)})", None

        # start evaluation
        # use python executable from the original environment to ensure all dependencies are available
        # 'cwd' is set to the submission/ subfolder so that submission_test.py resolves its relative
        # paths (./reports, ./your_submission_model, ./test_wav_files, ...) correctly
        print(f"Running submission_test.py for {task3_folder} ...")

        returncode, output, timed_out = _run_subprocess(
            cmd=[python_executable, "submission_test.py"],
            cwd=temp_path / "submission",
            timeout=1200,  # safety timeout to prevent infinite loops or very long runs, can be adjusted as needed
        )

        if timed_out:
            return "ERROR: Timeout (Runtime exceeded the limit)", None

        if returncode != 0:
            return f"ERROR: Runtime Error\n{output.strip()}", None
        
        # collect structured results from the yaml written by submission_test.py
        result_fields = _collect_results(temp_path)

        return output.strip(), result_fields


def evaluate_submissions():

    #check for root, python executable, submissions dir
    current_root = Path(__file__).parent.resolve()
    
    python_executable = sys.executable
    print(f"Used Python Environment: {python_executable}\n")
    
    if not SUBMISSIONS_DIR.exists():
        print(f"'{SUBMISSIONS_DIR}' doesnt exist.")
        return

    zip_files = list(SUBMISSIONS_DIR.glob("*.zip"))
    
    if not zip_files:
        print(f"No Zip files found in '{SUBMISSIONS_DIR}'.")
        return

    print(f"{len(zip_files)} Submissions found. Starting evaluation...\n")
    

    # iterate over all zips and evaluate them one by one, store the results in a list of dicts and csv
    results = []
    
    for idx, zip_file in enumerate(zip_files, 1):

        # discover all task3 submission folders inside this zip (can be more than one per zip)
        task3_folders = _get_task3_folders(zip_file)

        if not task3_folders:
            print(f"[{idx}/{len(zip_files)}] No task3 folders found in '{zip_file.name}', skipping.")
            continue

        print(f"[{idx}/{len(zip_files)}] Found {len(task3_folders)} task3 folder(s) in '{zip_file.name}': {task3_folders}")
        for task3_folder in task3_folders:
            print(f"[{idx}/{len(zip_files)}] Evaluating contestant: {task3_folder} ...", flush=True)

            # start isolated evaluation for this submission folder
            output, result_fields = evaluation_process(zip_file, task3_folder, current_root, python_executable)

            print(f"Done evaluating {task3_folder}.")

            # build result row: contestant name (folder) + either the per-metric fields or an error message
            row = {"Contestant": task3_folder}
            if result_fields is not None:
                row.update(result_fields)
            else:
                row["error"] = output

            results.append(row)
    
    # all_fields covers both the success columns and the error column
    all_fields = ["Contestant"] + RESULT_FIELDS + ["error"]

    RESULT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(RESULT_FILE, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=all_fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(results)
        
    print(f"\nEvaluation complete!")
    print(f"The results have been saved to '{RESULT_FILE}'.")


if __name__ == "__main__":
    evaluate_submissions()
    convert_csv_to_yaml(RESULT_FILE)