# --
# config inference



# inference handler
inference_handler:

  # add python paths (relative to inference handler or absolute)
  add_python_paths: []
  target_sample_rate: 24000
  target_wav_length_sec: 3

  # feature handler
  feature_handler:
    module: feature_handler
    attr: FeatureHandler
    args: []
    kwargs: 
      target_sample_rate: 24000
      window_len: 4096
      window_stride: 512
      window_scaling_bits: 12
      mel_n_channels: 40
      mel_low_hz: 125
      mel_high_hz: 7500
      mel_post_scaling_bits: 6
      transpose_features_extracted: True
      normalize_features: True
      to_float: True

  # model
  model:
    module: model_tiny_ml
    attr: ModelTinyMl
    args: []
    kwargs: 
      input_shape: 
      num_classes: 11