# --
# config inference

# test files
test_file_dir: './test_wav_files'
test_files_ext: '.wav'

# inference handler - pytorch
inference_handler:

  # add python paths (relative to inference handler or absolute)
  add_python_paths: []
  target_sample_rate: 24000
  target_wav_length_sec: 3
  model_dir: './your_submission_model'
  saved_model_extension: '.pth'
  tflite_model_extension: '.tflite'
  label_dict_yaml_path: './your_submission_model/label_dict.yaml'

  # feature handler
  feature_handler:
    module: feature_handler
    attr: FeatureHandler
    args: []
    kwargs: 
      target_sample_rate: 24000
      window_len: 4096
      window_stride: 512
      window_scaling_bits: 12
      mel_n_channels: 40
      mel_low_hz: 125
      mel_high_hz: 7500
      mel_post_scaling_bits: 6
      transpose_features_extracted: True
      normalize_features: True
      to_float: True
      add_channel_dimension: True
      add_batch_dimension: True
      channel_dimension_at_end: False

  # model
  model:
    module: pipeline_pytorch.model_tiny_ml
    attr: Baseline
    args: []
    kwargs: {}


# inference handler - pytorch
inference_handler_pytorch:

  # add python paths (relative to inference handler or absolute)
  add_python_paths: []
  target_sample_rate: 24000
  target_wav_length_sec: 3
  model_dir: './your_submission_model'
  saved_model_extension: '.pth'
  tflite_model_extension: '.tflite'
  label_dict_yaml_path: './your_submission_model/label_dict.yaml'

  # feature handler
  feature_handler:
    module: feature_handler
    attr: FeatureHandler
    args: []
    kwargs: 
      target_sample_rate: 24000
      window_len: 4096
      window_stride: 512
      window_scaling_bits: 12
      mel_n_channels: 40
      mel_low_hz: 125
      mel_high_hz: 7500
      mel_post_scaling_bits: 6
      transpose_features_extracted: True
      normalize_features: True
      to_float: True
      add_channel_dimension: True
      add_batch_dimension: True
      channel_dimension_at_end: False

  # model
  model:
    module: pipeline_pytorch.model_tiny_ml
    attr: Baseline
    args: []
    kwargs: {}


# inference handler - tensorflow
inference_handler_tensorflow:

  # add python paths (relative to inference handler or absolute)
  add_python_paths: []
  target_sample_rate: 24000
  target_wav_length_sec: 3
  model_dir: './your_submission_model'
  saved_model_extension: '.keras'
  tflite_model_extension: '.tflite'
  label_dict_yaml_path: './your_submission_model/label_dict.yaml'

  # feature handler
  feature_handler:
    module: feature_handler
    attr: FeatureHandler
    args: []
    kwargs: 
      target_sample_rate: 24000
      window_len: 4096
      window_stride: 512
      window_scaling_bits: 12
      mel_n_channels: 40
      mel_low_hz: 125
      mel_high_hz: 7500
      mel_post_scaling_bits: 6
      transpose_features_extracted: True
      normalize_features: True
      to_float: True
      add_channel_dimension: True
      add_batch_dimension: True
      channel_dimension_at_end: True

  # model
  model:
    module: keras
    attr: Model
    args: []
    kwargs: {}


# generate embedded code
generate_embedded_code:

  # gen code dir
  gen_code_dir: './your_generated_code'
  gen_code_source_folder_name: 'src'

  # replace with your serial device
  serial_device: '/dev/ttyUSB0'

  # quantize
  quantize: False