# --
# config inference

# test files
test_file_dir: './test_wav_files'
test_files_ext: '.wav'

# inference handler
inference_handler:

  # add python paths (relative to inference handler or absolute)
  add_python_paths: []
  target_sample_rate: 24000
  target_wav_length_sec: 3
  model_dir: './your_submission_model'
  saved_model_extension: '.pth'
  label_dict_yaml_path: './your_submission_model/label_dict.yaml'

  # feature handler
  feature_handler:
    module: feature_handler
    attr: FeatureHandler
    args: []
    kwargs: 
      target_sample_rate: 24000
      window_len: 4096
      window_stride: 512
      window_scaling_bits: 12
      mel_n_channels: 40
      mel_low_hz: 125
      mel_high_hz: 7500
      mel_post_scaling_bits: 6
      transpose_features_extracted: True
      normalize_features: True
      to_float: True

  # model
  model:
    module: model_tiny_ml
    attr: ModelTinyMl
    args: []
    kwargs: {}